id: P03207F7B
initial_creation_type: input
source_metadata:
  title: Āryaśūra Series
  language: en
  description: Texts by the great Indian master Āryaśūra, known to Tibetans as Lobpon
    Pawo (slob dpon dpa' bo), author of the famous Garland of Birth Stories (Jātakamālā)
  volume:
    802fec8566a4441a9ef8b21f43a95ccb:
      title: Short Praise of the Buddha's Deeds
      parent: Praise
    49f1225bc63a4c328c758901831614ab:
      title: Verses on the Buddha's Previous Lives
      parent: Prayers
created_at: '2022-03-01T02:08:51.633853'
last_modified_at: '2022-03-01T02:08:51.633859'
